# Generated by Django 3.0.7 on 2020-07-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_myimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
